// angular-sample/src/app/app.component.ts
import {Component} from '@angular/core';

@Component({
  selector   : 'app-root',
  templateUrl: './app.component.html',
  styleUrls  : ['./app.component.css'],
})
export class AppComponent {
  tab = 'panel1';

  /**
   * クリックしたときのイベントハンドラーです。
   * @param event イベントオブジェクトです。
   * @private
   */
   _handleClick(event: MouseEvent): void {
    // イベント発生源の要素を取得
    const element = event.currentTarget as HTMLElement;

    // aria-controls 属性の値を取得
    const tabState = element.getAttribute('aria-controls');

    // プロパティーを更新
    this.tab = tabState;
  }
}

<div>
  <ul role="tablist">
    <li role="presentation">
      <button role="tab"
              aria-controls="panel1"
              [attr.aria-selected]="tab === 'panel1'"
              (click)="_handleClick($event)">
        カベルネ・ソーヴィニョン
      </button>
    </li>
    <li role="presentation">
      <button role="tab"
              aria-controls="panel2"
              [attr.aria-selected]="tab === 'panel2'"
              (click)="_handleClick($event)">
        メルロー
      </button>
    </li>
    <li role="presentation">
      <button role="tab"
              aria-controls="panel3"
              [attr.aria-selected]="tab === 'panel3'"
              (click)="_handleClick($event)">
        ピノ・ノワール
      </button>
    </li>
  </ul>
  <div role="tabpanel"
       id="panel1"
       [attr.aria-hidden]="tab !== 'panel1'">
    カベルネ・ソーヴィニョンはブドウの一品種。赤ワインの中でも渋くて重い味わいが特徴です。
  </div>
  <div role="tabpanel"
       id="panel2"
       [attr.aria-hidden]="tab !== 'panel2'">
    メルローはブドウの一品種。味はカベルネ・ソーヴィニョンほど酸味やタンニンは強くなく、芳醇でまろやかで繊細な味わいです。
  </div>
  <div role="tabpanel"
       id="panel3"
       [attr.aria-hidden]="tab !== 'panel3'">
    ピノ・ノワールはブドウの一品種。カベルネ・ソーヴィニョンと対照的で比較的軽口な味わいです。
  </div>
</div>

// react-bad-sample/src/App.js
import React, {Component} from 'react';
import './App.css';

/**
 * タブUIのサンプルアプリケーションです。
 * @author Yasunobu Ikeda
 */
export default class App extends Component {

  constructor(props) {
    super(props);

    // ステートを定義
    this.state = {
      tab: 'panel1',
    };

    // イベントのスコープを登録（Reactの文化…）
    this._handleClick = this._handleClick.bind(this);
  }

  /**
   * クリックしたときのイベントハンドラーです。
   * @param event イベントオブジェクトです。
   * @private
   */
  _handleClick(event) {
    // イベント発生源の要素を取得
    const element = event.currentTarget;

    // aria-controls 属性の値を取得
    const tabState = element.dataset['controls'];

    // プロパティーを更新
    this.setState({
      tab: tabState,
    });
  }

  render() {
    return (
      <div>
        <ul>
          <li data-controls="panel1"
              className={this.state.tab === 'panel1' ? 'active' : ''}
              onClick={this._handleClick}>
            カベルネ・ソーヴィニョン
          </li>
          <li data-controls="panel2"
              className={this.state.tab === 'panel2' ? 'active' : ''}
              onClick={this._handleClick}>
            メルロー
          </li>
          <li data-controls="panel3"
              className={this.state.tab === 'panel3' ? 'active' : ''}
              onClick={this._handleClick}>
            ピノ・ノワール
          </li>
        </ul>
        <div id="panel1"
             className={this.state.tab === 'panel1' ? 'visible' : 'hidden'}>
          カベルネ・ソーヴィニョンはブドウの一品種。赤ワインの中でも渋くて重い味わいが特徴です。
        </div>
        <div id="panel2"
             className={this.state.tab === 'panel2' ? 'visible' : 'hidden'}>
          メルローはブドウの一品種。味はカベルネ・ソーヴィニョンほど酸味やタンニンは強くなく、芳醇でまろやかで繊細な味わいです。
        </div>
        <div id="panel3"
             className={this.state.tab === 'panel3' ? 'visible' : 'hidden'}>
          ピノ・ノワールはブドウの一品種。カベルネ・ソーヴィニョンと対照的で比較的軽口な味わいです。
        </div>
      </div>
    );
  }
}
